using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MUI.Generators
{
    [Generator]
    public sealed partial class UIGenerator : IIncrementalGenerator
    {
        private static readonly DiagnosticDescriptor InvalidContract = new DiagnosticDescriptor(
                    "MUI001", "Invalid MUI contract", "{0}", "MUI", DiagnosticSeverity.Error, true);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var types = context.SyntaxProvider.CreateSyntaxProvider(
                (node, token) => node is ClassDeclarationSyntax,
                (syntax, token) => syntax.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)syntax.Node) as INamedTypeSymbol);
            context.RegisterSourceOutput(types.Collect().Combine(context.CompilationProvider),
                (output, input) => Execute(new GenerationContext(output, input.Right), input.Left));
        }

        /// <summary>合并同一类型的分部声明，逐个输出绑定并汇总程序集注册入口。</summary>
        private static void Execute(GenerationContext context, ImmutableArray<INamedTypeSymbol> candidates)
        {
            if (!TryGetModule(context, out var moduleNamespace, out var registryName))
            {
                return;
            }

            var seen = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
            var generated = new List<string>();
            foreach (var type in candidates)
            {
                if (type == null || !seen.Add(type))
                {
                    continue;
                }

                if (!Relevant(type))
                {
                    continue;
                }

                try
                {
                    var result = Generate(context, type);
                    if (result != null)
                    {
                        generated.Add(result);
                    }
                    GenerateRoute(context, type, candidates);
                }
                catch (ContractException error)
                {
                    context.ReportDiagnostic(Diagnostic.Create(InvalidContract, error.Location, error.Message));
                }
            }
            if (generated.Count == 0)
            {
                return;
            }

            var registry = new StringBuilder("// <auto-generated/>\nnamespace ")
                .Append(moduleNamespace).Append("\n{\n    public static class ").Append(registryName).Append("\n    {\n        public static void Initialize()\n        {\n");
            foreach (var factory in generated.OrderBy(value => value, StringComparer.Ordinal))
            {
                registry.Append("            ").Append(factory).Append(".Register();\n");
            }

            registry.Append("        }\n    }\n}\n");
            context.AddSource(Identifier(moduleNamespace + "." + registryName) + ".g.cs", SourceText.From(registry.ToString(), Encoding.UTF8));
        }

        private static bool Relevant(INamedTypeSymbol type)
        {
            return Attribute(type, "MUI.ViewContractAttribute") != null ||
                Attribute(type, "MUI.Navigation.ViewRouteAttribute") != null || type.GetMembers().Any(member =>
                Attribute(member, "MUI.ObservablePropertyAttribute") != null ||
                Attribute(member, "MUI.OnChangedAttribute") != null ||
                Attribute(member, "MUI.NotifyPropertyChangedForAttribute") != null ||
                Attribute(member, "MUI.BindAttribute") != null ||
                Attribute(member, "MUI.CommandAttribute") != null ||
                Attribute(member, "MUI.BindCommandAttribute") != null);
        }

        /// <summary>校验模型契约并生成属性、绑定上下文、清单及工厂。</summary>
        private static string Generate(GenerationContext context, INamedTypeSymbol type)
        {
            ValidateTypeScope(context, type);
            if (type.IsStatic)
            {
                Fail(type, "Generated ViewModels must be instance classes.");
            }

            if (!DerivesFrom(type, "MUI.ViewModel"))
            {
                Fail(type, "A generated ViewModel must derive from MUI.ViewModel.");
            }

            foreach (var syntax in type.DeclaringSyntaxReferences)
            {
                if (syntax.GetSyntax() is ClassDeclarationSyntax declaration &&
                    !declaration.Modifiers.Any(SyntaxKind.PartialKeyword))
                {
                    Fail(type, "ViewModel declarations must be partial.");
                }
            }

            var contract = Attribute(type, "MUI.ViewContractAttribute");
            var resourceKey = contract == null ? null : contract.ConstructorArguments[0].Value as string;
            if (contract != null && string.IsNullOrWhiteSpace(resourceKey))
            {
                Fail(type, "ViewContract 必须指定非空资源键。");
            }

            var changeHandlers = CollectChangeHandlers(type);
            ValidateDependentNotifications(type);
            var properties = new StringBuilder();
            var bindings = new StringBuilder();
            var manifest = new StringBuilder();
            var names = CollectReservedMemberNames(context, type);
            var bindingCount = 0;
            var reverseSources = new Dictionary<string, string>(StringComparer.Ordinal);
            var targetWriters = new HashSet<string>(StringComparer.Ordinal);
            var commandEvents = new HashSet<string>(StringComparer.Ordinal);
            foreach (var member in CollectBindingMembers(type))
            {
                var inherited = !SymbolEqualityComparer.Default.Equals(member.ContainingType, type);
                var declaringType = member.ContainingType;
                var receiver = inherited ? "((" + TypeName(declaringType) + ")model)" : "model";
                // 继承成员只合并绑定，不向派生类重复生成属性或命令实例。
                var memberProperties = inherited ? new StringBuilder() : properties;
                var memberNames = inherited ? CollectReservedMemberNames(context, declaringType) : names;
                if (inherited && Attribute(member, "MUI.BindCommandAttribute") != null)
                {
                    var command = Attribute(member, "MUI.CommandAttribute");
                    var commandName = member is IMethodSymbol method && command != null
                        ? CommandPropertyName(method, command) : member.Name;
                    ValidateInheritedSource(type, member, commandName);
                }

                if (AppendCommand(context, declaringType, member, memberProperties, bindings, manifest,
                    memberNames, targetWriters, commandEvents, receiver))
                {
                    continue;
                }

                var observable = Attribute(member, "MUI.ObservablePropertyAttribute");
                var bindAttributes = member.GetAttributes().Where(a => a.AttributeClass?.ToDisplayString() == "MUI.BindAttribute").ToArray();
                if (observable == null && bindAttributes.Length == 0)
                {
                    continue;
                }

                string sourceName;
                ITypeSymbol sourceType;
                bool sourceReadable;
                bool sourceWritable;
                if (member is IFieldSymbol field)
                {
                    if (observable == null)
                    {
                        Fail(member, "A bound field requires ObservableProperty.");
                    }

                    if (field.IsStatic || field.IsReadOnly || field.IsConst)
                    {
                        Fail(member, "Observable fields must be writable instance fields.");
                    }

                    sourceName = ObservablePropertyName(field, observable);
                    if (!SyntaxFacts.IsValidIdentifier(sourceName) || sourceName == declaringType.Name || !memberNames.Add(sourceName))
                    {
                        Fail(member, "Generated property name is invalid or conflicts with another member: " + sourceName);
                    }

                    sourceType = field.Type;
                    sourceReadable = sourceWritable = true;
                    if (!inherited)
                    {
                        AppendBindingMetadata(context, properties, member, bindAttributes, false);
                        properties.Append("        public ").Append(TypeName(sourceType)).Append(' ').Append(Escape(sourceName)).Append("\n        {\n")
                            .Append("            get => this.").Append(Escape(field.Name)).Append(";\n");
                        AppendObservableSetter(properties, field, sourceName, changeHandlers);
                        properties.Append("        }\n");
                    }
                }
                else if (member is IPropertySymbol property)
                {
                    if (property.IsStatic || property.IsIndexer)
                    {
                        Fail(member, "Bindings require instance non-indexer properties.");
                    }

                    sourceName = property.Name;
                    sourceType = property.Type;
                    sourceReadable = Accessible(property.GetMethod);
                    sourceWritable = Accessible(property.SetMethod);
                }
                else
                {
                    Fail(member, "Unsupported binding member.");
                    return null;
                }

                if (inherited)
                {
                    ValidateInheritedSource(type, member, sourceName);
                }

                foreach (var attribute in bindAttributes)
                {
                    var elementName = attribute.ConstructorArguments[0].Value as string;
                    var targetName = attribute.ConstructorArguments[1].Value as string;
                    if (string.IsNullOrWhiteSpace(elementName) || string.IsNullOrWhiteSpace(targetName))
                    {
                        Fail(member, "Binding names must not be empty.");
                    }

                    var mode = attribute.ConstructorArguments.Length > 3 ? (int)attribute.ConstructorArguments[3].Value : 0;
                    if (mode < 0 || mode > 3)
                    {
                        Fail(member, "Unsupported binding mode.");
                    }

                    if (mode == 1 || mode == 2)
                    {
                        var input = elementName + "." + targetName;
                        if (reverseSources.TryGetValue(sourceName, out var previousInput))
                        {
                            Fail(member, "Multiple reverse bindings write " + sourceName + ": " + previousInput + ", " + input + ". Use one input binding or explicit business coordination.");
                        }

                        reverseSources.Add(sourceName, input);
                    }
                    var elementType = ResolveElement(context, attribute);
                    if (elementType == null)
                    {
                        Fail(member, "Use nameof(ElementType.Property), or set Bind.ElementType explicitly.");
                    }

                    ValidateElementType(context, member, elementType);
                    if (mode != 2 && !targetWriters.Add(elementName + "\0" + TypeName(elementType) + "\0" + targetName))
                    {
                        Fail(member, "Multiple bindings write the same Element property: " + elementName + "." + targetName);
                    }

                    var target = FindElementMember<IPropertySymbol>(elementType, targetName);
                    if (target == null || target.IsStatic || target.IsIndexer)
                    {
                        Fail(member, "Missing or ambiguous instance Element property: " + targetName);
                    }

                    if (mode != 2 && (!sourceReadable || !Accessible(target.SetMethod)))
                    {
                        Fail(member, "Forward binding requires a readable source and a public writable target.");
                    }

                    if ((mode == 1 || mode == 2) && (!sourceWritable || !Accessible(target.GetMethod)))
                    {
                        Fail(member, "Reverse binding requires a public writable source and readable target.");
                    }

                    var converter = attribute.ConstructorArguments.Length > 2 ? attribute.ConstructorArguments[2].Value as INamedTypeSymbol : null;
                    string forward = "value => value", reverse = "value => value";
                    string validationConverter = null;
                    var validationWriter = BuildValidationWriter(type, member, attribute, sourceName, mode, reverseSources);
                    if (converter != null)
                    {
                        // BindingContext 是独立的顶层类型，不能借用 ViewModel 的私有或受保护访问权限。
                        if (converter.IsUnboundGenericType ||
                            !context.Compilation.IsSymbolAccessibleWithin(converter, context.Compilation.Assembly))
                        {
                            Fail(member, "Converter must be a closed type accessible from the generated BindingContext.");
                        }

                        var validating = converter.AllInterfaces.Any(i => i.OriginalDefinition.ToDisplayString() == "MUI.IValidatingBindingConverter<TSource, TTarget>" &&
                            SymbolEqualityComparer.Default.Equals(i.TypeArguments[0], sourceType) &&
                            SymbolEqualityComparer.Default.Equals(i.TypeArguments[1], target.Type));
                        var valid = validating || converter.AllInterfaces.Any(i => i.OriginalDefinition.ToDisplayString() == "MUI.IBindingConverter<TSource, TTarget>" &&
                            SymbolEqualityComparer.Default.Equals(i.TypeArguments[0], sourceType) &&
                            SymbolEqualityComparer.Default.Equals(i.TypeArguments[1], target.Type));
                        if (!valid || converter.IsAbstract || !converter.InstanceConstructors.Any(c => c.Parameters.Length == 0 && c.DeclaredAccessibility == Accessibility.Public))
                        {
                            Fail(member, "Converter must implement the exact IBindingConverter or IValidatingBindingConverter source/target contract and have a public parameterless constructor.");
                        }

                        var local = "converter" + bindingCount;
                        bindings.Append(validating ? "            global::MUI.IValidatingBindingConverter<" : "            global::MUI.IBindingConverter<").Append(TypeName(sourceType)).Append(", ").Append(TypeName(target.Type)).Append("> ").Append(local).Append(" = new ").Append(TypeName(converter)).Append("();\n");
                        forward = local + ".Convert";
                        reverse = validating ? "null" : local + ".ConvertBack";
                        if (validating && (mode == 1 || mode == 2))
                        {
                            validationConverter = local + ".TryConvertBack";
                        }
                    }
                    else
                    {
                        var compilation = (CSharpCompilation)context.Compilation;
                        if (mode != 2 && !compilation.ClassifyConversion(sourceType, target.Type).IsImplicit)
                        {
                            Fail(member, "Forward types require an explicit binding converter.");
                        }

                        if ((mode == 1 || mode == 2) && !compilation.ClassifyConversion(target.Type, sourceType).IsImplicit)
                        {
                            Fail(member, "Reverse types require an explicit binding converter.");
                        }
                    }
                    var modeName = mode == 3 ? "OneTime" : mode == 0 ? "OneWay" : mode == 1 ? "TwoWay" : "OneWayToSource";
                    bindings.Append("            builder.Property<").Append(TypeName(elementType)).Append(", ").Append(TypeName(sourceType)).Append(", ").Append(TypeName(target.Type)).Append(">(\n")
                        .Append("                ").Append(Literal(elementName)).Append(", ").Append(Literal(sourceName)).Append(", ")
                        .Append(mode == 2 ? "null" : "model => " + receiver + "." + Escape(sourceName)).Append(", ")
                        .Append((mode == 0 || mode == 3) ? "null" : "(model, value) => " + receiver + "." + Escape(sourceName) + " = value").Append(",\n")
                        .Append("                ").Append(Literal(targetName)).Append(", ")
                        .Append((mode == 0 || mode == 3) ? "null" : "element => element." + Escape(targetName)).Append(", ")
                        .Append(mode == 2 ? "null" : "(element, value) => element." + Escape(targetName) + " = value").Append(",\n")
                        .Append("                ").Append(mode == 2 ? "null" : forward).Append(", ").Append((mode == 0 || mode == 3) ? "null" : reverse)
                        .Append(", global::MUI.BindingMode.").Append(modeName);
                    if (validationConverter != null || validationWriter != null)
                    {
                        bindings.Append(", tryConvertBack: ").Append(validationConverter ?? "null")
                            .Append(", writeValidation: ").Append(validationWriter ?? "null");
                    }
                    bindings.Append(");\n");
                    manifest.Append("                new global::MUI.BindingEntry(").Append(Literal(sourceName)).Append(", ").Append(Literal(elementName))
                        .Append(", typeof(").Append(TypeName(elementType)).Append("), ").Append(Literal(targetName)).Append(", global::MUI.BindingMode.").Append(modeName)
                        .Append(", global::MUI.BindingEntryKind.Property, \"Interactable\"");
                    AppendSourceLocation(manifest, attribute, member);
                    manifest.Append("),\n");
                    bindingCount++;
                }
            }
            var accessibility = type.DeclaredAccessibility == Accessibility.Public ? "public" : "internal";
            var bindingName = type.Name + "BindingContext";
            var factoryName = type.Name + "BindingFactory";
            if (HasSiblingType(type, bindingName) || HasSiblingType(type, factoryName))
            {
                Fail(type, "Generated binding type name conflicts with an existing type.");
            }

            var typeParameters = TypeParameters(type);
            var constraints = TypeConstraints(type);
            var output = new StringBuilder();
            output.Append("    [global::MUI.GeneratedBindingMetadata(1)]\n")
                .Append("    ").Append(accessibility).Append(" partial class ").Append(Escape(type.Name)).Append(typeParameters).Append(constraints).Append("\n    {\n").Append(properties).Append("    }\n\n")
                .Append("    ").Append(accessibility).Append(" sealed class ").Append(bindingName).Append(typeParameters).Append(" : global::MUI.BindingContext<").Append(TypeName(type)).Append(">").Append(constraints).Append("\n    {\n")
                .Append("        public ").Append(bindingName).Append("(global::MUI.IView view, ").Append(TypeName(type)).Append(" model)\n            : base(view, model)\n        {\n        }\n\n")
                .Append("        protected override void BuildBindings(global::MUI.BindingBuilder<").Append(TypeName(type)).Append("> builder)\n        {\n").Append(bindings).Append("        }\n    }\n\n")
                .Append("    [global::MUI.BindingFactory(typeof(").Append(TypeName(type.Arity == 0 ? type : type.ConstructUnboundGenericType())).Append("))]\n")
                .Append("    ").Append(accessibility).Append(" static class ").Append(factoryName).Append(typeParameters).Append(constraints).Append("\n    {\n")
                .Append("        /// <summary>来自当前模型 ViewContract 的资源键；未声明契约时为 null。</summary>\n")
                .Append("        public const string ResourceKey = ").Append(resourceKey == null ? "null" : Literal(resourceKey)).Append(";\n\n")
                .Append("        public static global::MUI.BindingManifest Manifest\n        {\n            get;\n        } = new global::MUI.BindingManifest(typeof(").Append(TypeName(type)).Append("),\n")
                .Append("            new global::MUI.BindingEntry[]\n            {\n").Append(manifest).Append("            });\n")
                .Append("        public static global::MUI.BindingContext<").Append(TypeName(type)).Append("> Create(global::MUI.IView view, ").Append(TypeName(type)).Append(" model)\n")
                .Append("            => new ").Append(bindingName).Append(typeParameters).Append("(view, model);\n")
                .Append("        public static void Register() => global::MUI.BindingRegistry.Register<").Append(TypeName(type)).Append(">(Create, Manifest);\n    }\n");
            context.AddSource(Identifier(type.ToDisplayString()) + ".Bindings.g.cs", SourceText.From(WrapTypeScope(type, output), Encoding.UTF8));
            // 开放类型没有可用的运行时绑定身份；由项目显式注册需要的闭合工厂。
            return type.Arity == 0 ? FactoryQualifiedName(type, factoryName) : null;
        }

        private static string TypeName(ITypeSymbol symbol) => symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, true);

        private static string Escape(string name) => "@" + name;

        private static string Identifier(string value) => "_" + string.Concat(value.Select(c => char.IsLetterOrDigit(c) ? c.ToString() : "_" + ((int)c).ToString("X4")));

        private static void Fail(ISymbol symbol, string message) => throw new ContractException(symbol.Locations.FirstOrDefault(), message);

        private sealed class ContractException : Exception
        {
            public ContractException(Location location, string message) : base(message)
            {
                Location = location;
            }

            public Location Location
            {
                get;
            }
        }

        private readonly struct GenerationContext
        {
            private readonly SourceProductionContext output;

            public GenerationContext(SourceProductionContext output, Compilation compilation)
            {
                this.output = output;
                Compilation = compilation;
            }

            public Compilation Compilation
            {
                get;
            }

            public void AddSource(string name, SourceText source)
            {
                // 保留模板有意拆开的参数、绑定和清单行，避免规范化将长声明压到一行。
                var layout = new MemberLayout();
                var syntax = CSharpSyntaxTree.ParseText(source.ToString()).GetRoot();
                var formatted = layout.Visit(syntax).ToFullString();
                if (layout.Conflicts.Count != 0)
                {
                    throw new InvalidOperationException(string.Join("\n", layout.Conflicts));
                }
                output.AddSource(name, SourceText.From(formatted, Encoding.UTF8));
            }

            public void ReportDiagnostic(Diagnostic diagnostic) => output.ReportDiagnostic(diagnostic);
        }
    }
}
